// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttcvvrnlmddqhiiyhwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dGN2dnJubG1kZHFoaWl5aHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDI2MzMsImV4cCI6MjA2NzIxODYzM30.DtO2WEQx6ttx4mLe2vVFBJya7O2wbnj0SBxeDlYJWlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});